user_1 = User.create(name: 'Denver', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Festival_de_M%C3%A1laga_2020_-_Miguel_Herr%C3%A1n-2_%28crop%29.jpg/428px-Festival_de_M%C3%A1laga_2020_-_Miguel_Herr%C3%A1n-2_%28crop%29.jpg', bio: 'Miguel Ángel García de la Herrán, best known as Miguel Herrán, is a Spanish actor. In 2016, he won the Goya Award for Best New Actor for his feature film debut in Nothing in Return. He gained notoriety for his performances in television series Élite and Money Heist.', email: 'denver@gmail.com', password: 'password')

user_2 = User.create(name: 'Professor', photo: 'https://dnm.nflximg.net/api/v6/n3FHGBVJhKMxWhzXOxu8erELTHY/AAAAQYkkPdrGOI22gZpTuGwUBMDPsoJrld06qnrX2JVB_alrvrOj2yLGKiyZbc2NKBsqyN2dqUn5a-E6ZmHTRMGQWxHzzrT0i3-GC4XRT8d2Xp-PG7RqOiaBV0Hmi35PsD6tN9uUC95qDtxppbVMx4_0l1RsBYFvhK8ZGC0h2iW-dusRqyhiiRHQ-fYttm330gpnTwXYuxr01vmCG4jBUKqkMSi3cw.png?r=ed9', bio: 'A criminal mastermind who has dedicated his life to planning the perfect heist, The Professor is often one step ahead of the police. He’s trained his hand-selected team of thieves well in the art of deception and manipulation.', email: 'professor@gmail.com', password: 'password')

user_3 = User.create(name: 'Lashana Lynch', photo: 'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRlKWbwHydx7WKay8hDAJvNUehrMn4g5V6DmwJft0KVd1fizSp8A2Jk3mkkl9VHtILV-gTQQ61wbLlwzkE', bio: 'Lashana Lynch is a British actress. She is best known for playing the role of Rosaline Capulet in the ABC period drama series Still Star-Crossed, Maria Rambeau in the Marvel Cinematic Universe films', email: 'lashana@gmail.com', password: 'password')

user_4 = User.create(name: 'Kevin Hart', photo: 'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRbBZSEcgw5ZhyhWCwb9Oqu_E5QVQHB34PkZdCCzNRe6LW59y_o5MHWNgpicivRfon8Buj9lMItZre4Hb8', bio: 'Kevin Darnell Hart is an American comedian and actor. Originally known as a stand-up comedian, he has since starred in Hollywood films and on TV. He has also released several well-received comedy albums.', email: 'kevin@gmail.com', password: 'password')

post_1 = Post.create(title: 'Exciting Heist Adventure', text: 'Join us as we embark on an exhilarating heist adventure!', author_id: user_1.id)
post_2 = Post.create(title: 'Mastermind Strategies', text: 'Learn the art of deception and manipulation from the brilliant Professor.', author_id: user_2.id)
post_3 = Post.create(title: 'Amazing Actress', text: 'Lashana Lynch\'s performances are captivating and inspiring.', author_id: user_3.id)
post_4 = Post.create(title: 'Laugh Out Loud with Kevin Hart', text: 'Get ready to burst into laughter with Kevin Hart\'s hilarious comedy.', author_id: user_4.id)
post_5 = Post.create(title: 'Unpredictable Twists', text: 'Discover unexpected twists and turns in our thrilling heist series!', author_id: user_1.id)
post_6 = Post.create(title: 'Behind the Scenes', text: 'Explore the behind-the-scenes secrets of our action-packed TV show.', author_id: user_2.id)
post_7 = Post.create(title: 'Comedy Album Release', text: 'Check out Kevin Hart\'s latest comedy album for non-stop laughter!', author_id: user_4.id)
post_8 = Post.create(title: 'Hilarious Stand-Up Special', text: 'Catch Kevin Hart\'s latest stand-up special for an evening filled with laughter!', author_id: user_4.id)
post_9 = Post.create(title: 'Film Recommendation', text: 'Don\'t miss Kevin Hart\'s fantastic performance in the must-watch comedy film!', author_id: user_4.id)

comment_1 = Comment.create(text: 'This is a great post!', author_id: user_1.id, post_id: post_1.id)
comment_2 = Comment.create(text: 'I love this post!', author_id: user_2.id, post_id: post_2.id)
comment_3 = Comment.create(text: 'This is a great post!', author_id: user_3.id, post_id: post_3.id)
comment_4 = Comment.create(text: 'I love this post!', author_id: user_4.id, post_id: post_4.id)
comment_5 = Comment.create(text: 'This is a great post!', author_id: user_1.id, post_id: post_5.id)
comment_6 = Comment.create(text: 'I love this post!', author_id: user_2.id, post_id: post_6.id)
comment_7 = Comment.create(text: 'This is a great post!', author_id: user_4.id, post_id: post_7.id)
comment_8 = Comment.create(text: 'I love this post!', author_id: user_4.id, post_id: post_9.id)
comment_9 = Comment.create(text: 'This is a great post!', author_id: user_4.id, post_id: post_9.id)
comment_10 = Comment.create(text: 'I love this post!', author_id: user_3.id, post_id: post_9.id)
comment_11 = Comment.create(text: 'This is a great post!', author_id: user_2.id, post_id: post_9.id)
comment_12 = Comment.create(text: 'I love this post!', author_id: user_1.id, post_id: post_9.id)
comment_13 = Comment.create(text: 'This is a great post!', author_id: user_4.id, post_id: post_9.id)

like_1 = Like.create(author_id: user_1.id, post_id: post_1.id)
like_2 = Like.create(author_id: user_2.id, post_id: post_2.id)
like_3 = Like.create(author_id: user_3.id, post_id: post_3.id)
like_4 = Like.create(author_id: user_4.id, post_id: post_4.id)
like_5 = Like.create(author_id: user_1.id, post_id: post_5.id)
like_6 = Like.create(author_id: user_2.id, post_id: post_6.id)
